name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.200"

      - name: Package app
        run: make package

      - name: Push packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.FEEDZ_IO_TOKEN }} --source https://f.feedz.io/nvd/nyancat-cs/nuget/index.json --skip-duplicate
